name: publish

on: [push]

jobs:
  build-and-publish-server-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and publish web Docker image
        run: |
          echo $PAT | docker login ghcr.io -u mfalicoff --password-stdin
          cd server
          docker build . --tag ghcr.io/mfalicoff/infra-server:latest
          docker push ghcr.io/mfalicoff/infra-server:latest
        env:
          PAT: ${{ secrets.PAT }}