name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the hello-world Docker image
        run: |
          echo $PAT | docker login ghcr.io -u mfalicoff --password-stdin
          cd client
          docker build . --tag ghcr.io/mfalicoff/infra-web:latest
        env:
          PAT: ${{ secrets.PAT }}